alias: Heating_BR1_ResetTemperature
description: "Reset the temperature of the TRV in Bedroom 01"
triggers:
  - trigger: numeric_state
    entity_id:
      - climate.rv_br1_gf_thermostat
    attribute: temperature
    above: 26
conditions: []
actions:
  - action: climate.set_temperature
    metadata: {}
    data:
      temperature: 25
    target:
      entity_id: climate.rv_br1_gf_thermostat
mode: single
